// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/encmempool/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCommitTx records sha256(reveal_tx || salt) at the current block height.
type MsgCommitTx struct {
	// sender is the committer (the only one who can reveal this commit).
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// commit_hash = sha256(reveal_tx || salt), 32 bytes.
	CommitHash []byte `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
}

func (m *MsgCommitTx) Reset()         { *m = MsgCommitTx{} }
func (m *MsgCommitTx) String() string { return proto.CompactTextString(m) }
func (*MsgCommitTx) ProtoMessage()    {}
func (*MsgCommitTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec253a7da7cb1f1f, []int{0}
}
func (m *MsgCommitTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitTx.Merge(m, src)
}
func (m *MsgCommitTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitTx proto.InternalMessageInfo

func (m *MsgCommitTx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCommitTx) GetCommitHash() []byte {
	if m != nil {
		return m.CommitHash
	}
	return nil
}

type MsgCommitTxResponse struct {
	// commit_height is the block height the commit was recorded at.
	CommitHeight uint64 `protobuf:"varint,1,opt,name=commit_height,json=commitHeight,proto3" json:"commit_height,omitempty"`
	// seq identifies this commit among the sender's commits at that height.
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (m *MsgCommitTxResponse) Reset()         { *m = MsgCommitTxResponse{} }
func (m *MsgCommitTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCommitTxResponse) ProtoMessage()    {}
func (*MsgCommitTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec253a7da7cb1f1f, []int{1}
}
func (m *MsgCommitTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitTxResponse.Merge(m, src)
}
func (m *MsgCommitTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitTxResponse proto.InternalMessageInfo

func (m *MsgCommitTxResponse) GetCommitHeight() uint64 {
	if m != nil {
		return m.CommitHeight
	}
	return 0
}

func (m *MsgCommitTxResponse) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// MsgRevealTx reveals the committed body; rejected before commit_height +
// reveal_delay, or if sha256(reveal_tx || salt) does not match the commitment.
type MsgRevealTx struct {
	// sender must equal the original committer.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// commit_height is the height the matching commit was recorded at.
	CommitHeight uint64 `protobuf:"varint,2,opt,name=commit_height,json=commitHeight,proto3" json:"commit_height,omitempty"`
	// seq identifies the specific commit.
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// reveal_tx is the raw committed payload (opaque to this module).
	RevealTx []byte `protobuf:"bytes,4,opt,name=reveal_tx,json=revealTx,proto3" json:"reveal_tx,omitempty"`
	// salt is the commitment blinding factor.
	Salt []byte `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (m *MsgRevealTx) Reset()         { *m = MsgRevealTx{} }
func (m *MsgRevealTx) String() string { return proto.CompactTextString(m) }
func (*MsgRevealTx) ProtoMessage()    {}
func (*MsgRevealTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec253a7da7cb1f1f, []int{2}
}
func (m *MsgRevealTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevealTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevealTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevealTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevealTx.Merge(m, src)
}
func (m *MsgRevealTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevealTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevealTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevealTx proto.InternalMessageInfo

func (m *MsgRevealTx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRevealTx) GetCommitHeight() uint64 {
	if m != nil {
		return m.CommitHeight
	}
	return 0
}

func (m *MsgRevealTx) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *MsgRevealTx) GetRevealTx() []byte {
	if m != nil {
		return m.RevealTx
	}
	return nil
}

func (m *MsgRevealTx) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type MsgRevealTxResponse struct {
}

func (m *MsgRevealTxResponse) Reset()         { *m = MsgRevealTxResponse{} }
func (m *MsgRevealTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevealTxResponse) ProtoMessage()    {}
func (*MsgRevealTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec253a7da7cb1f1f, []int{3}
}
func (m *MsgRevealTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevealTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevealTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevealTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevealTxResponse.Merge(m, src)
}
func (m *MsgRevealTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevealTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevealTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevealTxResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCommitTx)(nil), "cosmos.evm.encmempool.v1.MsgCommitTx")
	proto.RegisterType((*MsgCommitTxResponse)(nil), "cosmos.evm.encmempool.v1.MsgCommitTxResponse")
	proto.RegisterType((*MsgRevealTx)(nil), "cosmos.evm.encmempool.v1.MsgRevealTx")
	proto.RegisterType((*MsgRevealTxResponse)(nil), "cosmos.evm.encmempool.v1.MsgRevealTxResponse")
}

func init() { proto.RegisterFile("cosmos/evm/encmempool/v1/tx.proto", fileDescriptor_ec253a7da7cb1f1f) }

var fileDescriptor_ec253a7da7cb1f1f = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xcd, 0x5e, 0x7c, 0xa7, 0xdc, 0x5e, 0x90, 0x60, 0x09, 0xc2, 0x18, 0xc9, 0x04, 0x23, 0xa4,
	0x28, 0x52, 0x6c, 0x02, 0x1d, 0x1d, 0xa1, 0xa1, 0x20, 0x8d, 0xa1, 0xa2, 0x49, 0x1c, 0x67, 0xb5,
	0xb6, 0x94, 0xf5, 0x1a, 0xcf, 0x62, 0x99, 0x0e, 0x51, 0x52, 0x21, 0xf1, 0x47, 0x52, 0xf0, 0x23,
	0x28, 0x23, 0x2a, 0x44, 0x85, 0x92, 0x22, 0x7f, 0x03, 0x65, 0xd7, 0x36, 0x16, 0x28, 0x7c, 0x35,
	0xd6, 0xcc, 0x9b, 0xe7, 0x79, 0x33, 0x6f, 0x07, 0xdf, 0x0e, 0x05, 0x70, 0x01, 0x1e, 0xcd, 0xb9,
	0x47, 0x93, 0x90, 0x53, 0x9e, 0x0a, 0xb1, 0xf2, 0xf2, 0xb1, 0x27, 0x0b, 0x37, 0xcd, 0x84, 0x14,
	0xc4, 0xd4, 0x14, 0x97, 0xe6, 0xdc, 0xfd, 0x41, 0x71, 0xf3, 0xb1, 0x75, 0x25, 0xe0, 0x71, 0x22,
	0x3c, 0xf5, 0xd5, 0x64, 0xeb, 0x7a, 0xd9, 0x8f, 0x03, 0x3b, 0x34, 0xe1, 0xc0, 0xca, 0xc2, 0x0d,
	0x5d, 0x98, 0xa9, 0xcc, 0x2b, 0x5b, 0xea, 0x52, 0x8f, 0x09, 0x26, 0x34, 0x7e, 0x88, 0x34, 0xea,
	0x7c, 0x40, 0xf8, 0x62, 0x0a, 0xec, 0xb1, 0xe0, 0x3c, 0x96, 0xcf, 0x0b, 0x72, 0x0f, 0x9f, 0x01,
	0x4d, 0x96, 0x34, 0x33, 0x51, 0x1f, 0x0d, 0xce, 0x27, 0xe6, 0xe7, 0x8f, 0xa3, 0x5e, 0xd9, 0xe7,
	0xd1, 0x72, 0x99, 0x51, 0x80, 0x67, 0x32, 0x8b, 0x13, 0xe6, 0x97, 0x3c, 0x72, 0x0b, 0x5f, 0x84,
	0xea, 0xef, 0x59, 0x14, 0x40, 0x64, 0x9e, 0xf4, 0xd1, 0xa0, 0xeb, 0x63, 0x0d, 0x3d, 0x09, 0x20,
	0x7a, 0x38, 0x7e, 0xbb, 0x5f, 0x0f, 0x4b, 0xf6, 0xbb, 0xfd, 0x7a, 0x78, 0xc4, 0x8c, 0xc6, 0x14,
	0xce, 0x53, 0x7c, 0xb5, 0x91, 0xfa, 0x14, 0x52, 0x91, 0x00, 0x25, 0x77, 0xf0, 0xa5, 0x4a, 0x8a,
	0xc6, 0x2c, 0x92, 0x6a, 0x46, 0xc3, 0xef, 0x96, 0x62, 0x0a, 0x23, 0x97, 0x71, 0x1b, 0xe8, 0x4b,
	0x35, 0x87, 0xe1, 0x1f, 0x42, 0xe7, 0xab, 0xde, 0xd1, 0xa7, 0x39, 0x0d, 0x56, 0xff, 0xb5, 0xe3,
	0x2f, 0xc2, 0x27, 0xc7, 0x85, 0xdb, 0xb5, 0x30, 0xb9, 0x89, 0xcf, 0x33, 0x25, 0x3a, 0x93, 0x85,
	0x69, 0x28, 0x63, 0x3a, 0x59, 0x35, 0x05, 0xc1, 0x06, 0x04, 0x2b, 0x69, 0x9e, 0x2a, 0x5c, 0xc5,
	0xff, 0x60, 0x55, 0xb5, 0x8c, 0x73, 0x4d, 0x59, 0x55, 0xa5, 0x95, 0x55, 0xf7, 0x37, 0x08, 0xb7,
	0xa7, 0xc0, 0xc8, 0x1c, 0x77, 0xea, 0xb7, 0xbd, 0xeb, 0x1e, 0xbb, 0x31, 0xb7, 0xe1, 0xb6, 0x35,
	0xfa, 0x2b, 0x5a, 0xfd, 0x28, 0x73, 0xdc, 0xa9, 0x9d, 0xfd, 0xbd, 0x42, 0x45, 0xfb, 0x83, 0xc2,
	0xcf, 0xbb, 0x58, 0xa7, 0x6f, 0xf6, 0xeb, 0x21, 0x9a, 0x4c, 0x3e, 0x6d, 0x6d, 0xb4, 0xd9, 0xda,
	0xe8, 0xdb, 0xd6, 0x46, 0xef, 0x77, 0x76, 0x6b, 0xb3, 0xb3, 0x5b, 0x5f, 0x76, 0x76, 0xeb, 0xc5,
	0x80, 0xc5, 0x32, 0x7a, 0xb5, 0x70, 0x43, 0xc1, 0xbd, 0x86, 0x63, 0x45, 0xd3, 0x33, 0xf9, 0x3a,
	0xa5, 0xb0, 0x38, 0x53, 0x57, 0xff, 0xe0, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xc8, 0x5b,
	0x54, 0x91, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CommitTx records a hash-commitment to a future transaction.
	CommitTx(ctx context.Context, in *MsgCommitTx, opts ...grpc.CallOption) (*MsgCommitTxResponse, error)
	// RevealTx reveals the committed transaction body after the reveal delay.
	RevealTx(ctx context.Context, in *MsgRevealTx, opts ...grpc.CallOption) (*MsgRevealTxResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CommitTx(ctx context.Context, in *MsgCommitTx, opts ...grpc.CallOption) (*MsgCommitTxResponse, error) {
	out := new(MsgCommitTxResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.encmempool.v1.Msg/CommitTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealTx(ctx context.Context, in *MsgRevealTx, opts ...grpc.CallOption) (*MsgRevealTxResponse, error) {
	out := new(MsgRevealTxResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.encmempool.v1.Msg/RevealTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CommitTx records a hash-commitment to a future transaction.
	CommitTx(context.Context, *MsgCommitTx) (*MsgCommitTxResponse, error)
	// RevealTx reveals the committed transaction body after the reveal delay.
	RevealTx(context.Context, *MsgRevealTx) (*MsgRevealTxResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CommitTx(ctx context.Context, req *MsgCommitTx) (*MsgCommitTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTx not implemented")
}
func (*UnimplementedMsgServer) RevealTx(ctx context.Context, req *MsgRevealTx) (*MsgRevealTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealTx not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CommitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCommitTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CommitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.encmempool.v1.Msg/CommitTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CommitTx(ctx, req.(*MsgCommitTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.encmempool.v1.Msg/RevealTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealTx(ctx, req.(*MsgRevealTx))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.encmempool.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitTx",
			Handler:    _Msg_CommitTx_Handler,
		},
		{
			MethodName: "RevealTx",
			Handler:    _Msg_RevealTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/encmempool/v1/tx.proto",
}

func (m *MsgCommitTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommitHash) > 0 {
		i -= len(m.CommitHash)
		copy(dAtA[i:], m.CommitHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CommitHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCommitTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Seq != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x10
	}
	if m.CommitHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CommitHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevealTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevealTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevealTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RevealTx) > 0 {
		i -= len(m.RevealTx)
		copy(dAtA[i:], m.RevealTx)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RevealTx)))
		i--
		dAtA[i] = 0x22
	}
	if m.Seq != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x18
	}
	if m.CommitHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CommitHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevealTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevealTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevealTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCommitTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CommitHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCommitTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommitHeight != 0 {
		n += 1 + sovTx(uint64(m.CommitHeight))
	}
	if m.Seq != 0 {
		n += 1 + sovTx(uint64(m.Seq))
	}
	return n
}

func (m *MsgRevealTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CommitHeight != 0 {
		n += 1 + sovTx(uint64(m.CommitHeight))
	}
	if m.Seq != 0 {
		n += 1 + sovTx(uint64(m.Seq))
	}
	l = len(m.RevealTx)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevealTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCommitTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHash = append(m.CommitHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitHash == nil {
				m.CommitHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHeight", wireType)
			}
			m.CommitHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevealTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevealTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevealTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHeight", wireType)
			}
			m.CommitHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealTx", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevealTx = append(m.RevealTx[:0], dAtA[iNdEx:postIndex]...)
			if m.RevealTx == nil {
				m.RevealTx = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevealTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevealTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevealTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
