// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/contest/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterShowcase registers/approves a showcase app (admin-gated).
type MsgRegisterShowcase struct {
	// admin is the bech32 address authorized to manage the registry (params.admin).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// address is the contract to register (EVM lower-hex 0x… or bech32 wasm addr).
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// dev is the identifier credited for Developer-track points.
	Dev string `protobuf:"bytes,3,opt,name=dev,proto3" json:"dev,omitempty"`
	// vm is "evm" or "wasm".
	Vm string `protobuf:"bytes,4,opt,name=vm,proto3" json:"vm,omitempty"`
}

func (m *MsgRegisterShowcase) Reset()         { *m = MsgRegisterShowcase{} }
func (m *MsgRegisterShowcase) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterShowcase) ProtoMessage()    {}
func (*MsgRegisterShowcase) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{0}
}
func (m *MsgRegisterShowcase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterShowcase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterShowcase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterShowcase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterShowcase.Merge(m, src)
}
func (m *MsgRegisterShowcase) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterShowcase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterShowcase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterShowcase proto.InternalMessageInfo

func (m *MsgRegisterShowcase) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgRegisterShowcase) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgRegisterShowcase) GetDev() string {
	if m != nil {
		return m.Dev
	}
	return ""
}

func (m *MsgRegisterShowcase) GetVm() string {
	if m != nil {
		return m.Vm
	}
	return ""
}

type MsgRegisterShowcaseResponse struct {
}

func (m *MsgRegisterShowcaseResponse) Reset()         { *m = MsgRegisterShowcaseResponse{} }
func (m *MsgRegisterShowcaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterShowcaseResponse) ProtoMessage()    {}
func (*MsgRegisterShowcaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{1}
}
func (m *MsgRegisterShowcaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterShowcaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterShowcaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterShowcaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterShowcaseResponse.Merge(m, src)
}
func (m *MsgRegisterShowcaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterShowcaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterShowcaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterShowcaseResponse proto.InternalMessageInfo

// MsgRemoveShowcase removes a showcase app from the registry (admin-gated).
type MsgRemoveShowcase struct {
	// admin is the bech32 address authorized to manage the registry (params.admin).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// address is the contract to remove.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgRemoveShowcase) Reset()         { *m = MsgRemoveShowcase{} }
func (m *MsgRemoveShowcase) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveShowcase) ProtoMessage()    {}
func (*MsgRemoveShowcase) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{2}
}
func (m *MsgRemoveShowcase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveShowcase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveShowcase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveShowcase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveShowcase.Merge(m, src)
}
func (m *MsgRemoveShowcase) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveShowcase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveShowcase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveShowcase proto.InternalMessageInfo

func (m *MsgRemoveShowcase) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgRemoveShowcase) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MsgRemoveShowcaseResponse struct {
}

func (m *MsgRemoveShowcaseResponse) Reset()         { *m = MsgRemoveShowcaseResponse{} }
func (m *MsgRemoveShowcaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveShowcaseResponse) ProtoMessage()    {}
func (*MsgRemoveShowcaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{3}
}
func (m *MsgRemoveShowcaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveShowcaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveShowcaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveShowcaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveShowcaseResponse.Merge(m, src)
}
func (m *MsgRemoveShowcaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveShowcaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveShowcaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveShowcaseResponse proto.InternalMessageInfo

// MsgSetPasskeyEnabled toggles the experimental passkey ante path (admin-gated).
type MsgSetPasskeyEnabled struct {
	// admin is the bech32 address authorized to manage the registry (params.admin).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// enabled turns the passkey ante path on (true) or off (false).
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *MsgSetPasskeyEnabled) Reset()         { *m = MsgSetPasskeyEnabled{} }
func (m *MsgSetPasskeyEnabled) String() string { return proto.CompactTextString(m) }
func (*MsgSetPasskeyEnabled) ProtoMessage()    {}
func (*MsgSetPasskeyEnabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{4}
}
func (m *MsgSetPasskeyEnabled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetPasskeyEnabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetPasskeyEnabled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetPasskeyEnabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetPasskeyEnabled.Merge(m, src)
}
func (m *MsgSetPasskeyEnabled) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetPasskeyEnabled) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetPasskeyEnabled.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetPasskeyEnabled proto.InternalMessageInfo

func (m *MsgSetPasskeyEnabled) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgSetPasskeyEnabled) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type MsgSetPasskeyEnabledResponse struct {
}

func (m *MsgSetPasskeyEnabledResponse) Reset()         { *m = MsgSetPasskeyEnabledResponse{} }
func (m *MsgSetPasskeyEnabledResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetPasskeyEnabledResponse) ProtoMessage()    {}
func (*MsgSetPasskeyEnabledResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{5}
}
func (m *MsgSetPasskeyEnabledResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetPasskeyEnabledResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetPasskeyEnabledResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetPasskeyEnabledResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetPasskeyEnabledResponse.Merge(m, src)
}
func (m *MsgSetPasskeyEnabledResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetPasskeyEnabledResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetPasskeyEnabledResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetPasskeyEnabledResponse proto.InternalMessageInfo

// MsgSetAdmin rotates/revokes the contest admin. Gov-gated (authority = gov).
type MsgSetAdmin struct {
	// authority must be the x/gov module account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// admin is the new params.admin (bech32, or "" to disable admin actions).
	Admin string `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (m *MsgSetAdmin) Reset()         { *m = MsgSetAdmin{} }
func (m *MsgSetAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgSetAdmin) ProtoMessage()    {}
func (*MsgSetAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{6}
}
func (m *MsgSetAdmin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetAdmin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAdmin.Merge(m, src)
}
func (m *MsgSetAdmin) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAdmin proto.InternalMessageInfo

func (m *MsgSetAdmin) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetAdmin) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

type MsgSetAdminResponse struct {
}

func (m *MsgSetAdminResponse) Reset()         { *m = MsgSetAdminResponse{} }
func (m *MsgSetAdminResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetAdminResponse) ProtoMessage()    {}
func (*MsgSetAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb10302077a67e9, []int{7}
}
func (m *MsgSetAdminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetAdminResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetAdminResponse.Merge(m, src)
}
func (m *MsgSetAdminResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetAdminResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterShowcase)(nil), "cosmos.evm.contest.v1.MsgRegisterShowcase")
	proto.RegisterType((*MsgRegisterShowcaseResponse)(nil), "cosmos.evm.contest.v1.MsgRegisterShowcaseResponse")
	proto.RegisterType((*MsgRemoveShowcase)(nil), "cosmos.evm.contest.v1.MsgRemoveShowcase")
	proto.RegisterType((*MsgRemoveShowcaseResponse)(nil), "cosmos.evm.contest.v1.MsgRemoveShowcaseResponse")
	proto.RegisterType((*MsgSetPasskeyEnabled)(nil), "cosmos.evm.contest.v1.MsgSetPasskeyEnabled")
	proto.RegisterType((*MsgSetPasskeyEnabledResponse)(nil), "cosmos.evm.contest.v1.MsgSetPasskeyEnabledResponse")
	proto.RegisterType((*MsgSetAdmin)(nil), "cosmos.evm.contest.v1.MsgSetAdmin")
	proto.RegisterType((*MsgSetAdminResponse)(nil), "cosmos.evm.contest.v1.MsgSetAdminResponse")
}

func init() { proto.RegisterFile("cosmos/evm/contest/v1/tx.proto", fileDescriptor_1cb10302077a67e9) }

var fileDescriptor_1cb10302077a67e9 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x1c, 0xc5, 0x73, 0x09, 0x85, 0xf6, 0x90, 0xaa, 0xc6, 0xa4, 0xc2, 0x75, 0xe1, 0x84, 0x2c, 0x7e,
	0x54, 0x46, 0xd8, 0xa4, 0x11, 0x1d, 0xb2, 0xa0, 0x56, 0x62, 0x8c, 0x84, 0x9c, 0xad, 0x0b, 0x72,
	0xe2, 0xd3, 0xc5, 0xa2, 0xe7, 0x8b, 0x7c, 0x17, 0xd3, 0x6c, 0x88, 0x91, 0x01, 0x21, 0x26, 0xfe,
	0x8c, 0x0c, 0x0c, 0xac, 0x6c, 0x8c, 0x15, 0x13, 0x23, 0x4a, 0x86, 0xfc, 0x1b, 0xc8, 0x77, 0xb6,
	0x9b, 0x62, 0xa7, 0x0d, 0x88, 0x25, 0xf2, 0xf7, 0x7d, 0x9f, 0xdf, 0x7d, 0x6c, 0xbd, 0x18, 0xa2,
	0x3e, 0xe3, 0x94, 0x71, 0x07, 0xc7, 0xd4, 0xe9, 0xb3, 0x50, 0x60, 0x2e, 0x9c, 0xb8, 0xe9, 0x88,
	0x53, 0x7b, 0x18, 0x31, 0xc1, 0xb4, 0x6d, 0xb5, 0xb7, 0x71, 0x4c, 0xed, 0x74, 0x6f, 0xc7, 0x4d,
	0xa3, 0xee, 0xd1, 0x20, 0x64, 0x8e, 0xfc, 0x55, 0x4e, 0xe3, 0x76, 0x9a, 0x44, 0x39, 0x49, 0x12,
	0x28, 0x27, 0xe9, 0x62, 0x47, 0x2d, 0x5e, 0xc9, 0xc9, 0x49, 0xf3, 0xd4, 0xaa, 0x41, 0x18, 0x61,
	0x4a, 0x4f, 0xae, 0x94, 0x6a, 0x7e, 0x05, 0xf0, 0x56, 0x87, 0x13, 0x17, 0x93, 0x80, 0x0b, 0x1c,
	0x75, 0x07, 0xec, 0x4d, 0xdf, 0xe3, 0x58, 0xb3, 0xe1, 0x9a, 0xe7, 0xd3, 0x20, 0xd4, 0xc1, 0x3d,
	0xb0, 0xb7, 0x71, 0xa4, 0xff, 0xf8, 0xf2, 0xa4, 0x91, 0xc6, 0x1d, 0xfa, 0x7e, 0x84, 0x39, 0xef,
	0x8a, 0x28, 0x08, 0x89, 0xab, 0x6c, 0x9a, 0x0e, 0x6f, 0x78, 0x4a, 0xd7, 0xab, 0xc9, 0x1d, 0x6e,
	0x36, 0x6a, 0x5b, 0xb0, 0xe6, 0xe3, 0x58, 0xaf, 0x49, 0x35, 0xb9, 0xd4, 0x36, 0x61, 0x35, 0xa6,
	0xfa, 0x35, 0x29, 0x54, 0x63, 0xda, 0x7e, 0xf6, 0x6e, 0x3e, 0xb1, 0x54, 0xce, 0xfb, 0xf9, 0xc4,
	0x7a, 0x58, 0xf2, 0x9a, 0x4a, 0x10, 0xcd, 0xbb, 0x70, 0xb7, 0x44, 0x76, 0x31, 0x1f, 0xb2, 0x90,
	0x63, 0xf3, 0x13, 0x80, 0x75, 0xb9, 0xa7, 0x2c, 0xc6, 0xff, 0xff, 0xb9, 0xda, 0xad, 0x8b, 0xd4,
	0xf7, 0x97, 0x51, 0x2f, 0x1e, 0x6f, 0xee, 0xc2, 0x9d, 0x82, 0x98, 0x13, 0x7f, 0x06, 0xb0, 0xd1,
	0xe1, 0xa4, 0x8b, 0xc5, 0x4b, 0x8f, 0xf3, 0xd7, 0x78, 0xfc, 0x22, 0xf4, 0x7a, 0x27, 0xd8, 0xff,
	0x17, 0x68, 0xac, 0x6e, 0x95, 0xd0, 0xeb, 0x6e, 0x36, 0xb6, 0x0f, 0x2e, 0x42, 0x3f, 0x2a, 0x87,
	0x2e, 0x10, 0x98, 0x08, 0xde, 0x29, 0xd3, 0x73, 0xf4, 0x0f, 0x00, 0xde, 0x54, 0x86, 0x43, 0x49,
	0x70, 0x00, 0x37, 0xbc, 0x91, 0x18, 0xb0, 0x28, 0x10, 0xe3, 0x2b, 0xa9, 0xcf, 0xad, 0x5a, 0x23,
	0x7b, 0x52, 0xf5, 0xb2, 0xd5, 0xd0, 0x6e, 0x26, 0xd4, 0xe7, 0xae, 0x84, 0x1c, 0x2d, 0x25, 0x97,
	0x00, 0xe6, 0xb6, 0xac, 0x75, 0x36, 0x66, 0x9c, 0xfb, 0xdf, 0x6a, 0xb0, 0xd6, 0xe1, 0x44, 0x8b,
	0xe0, 0x56, 0xa1, 0xf2, 0x96, 0x5d, 0xfa, 0xff, 0xb3, 0x4b, 0x4a, 0x66, 0xec, 0xaf, 0xee, 0xcd,
	0xce, 0xd6, 0x4e, 0xe0, 0xe6, 0x1f, 0x65, 0xdc, 0xbb, 0x2c, 0x65, 0xd1, 0x69, 0x3c, 0x5d, 0xd5,
	0x99, 0x9f, 0x36, 0x82, 0xf5, 0x62, 0x91, 0x1e, 0x2f, 0x8f, 0x29, 0x98, 0x8d, 0xd6, 0x5f, 0x98,
	0xf3, 0x63, 0x8f, 0xe1, 0x7a, 0x5e, 0x02, 0xf3, 0xd2, 0x00, 0xe9, 0x31, 0xac, 0xab, 0x3d, 0x59,
	0xb6, 0xb1, 0xf6, 0x76, 0x3e, 0xb1, 0xc0, 0xd1, 0xf3, 0xef, 0x53, 0x04, 0xce, 0xa6, 0x08, 0xfc,
	0x9a, 0x22, 0xf0, 0x71, 0x86, 0x2a, 0x67, 0x33, 0x54, 0xf9, 0x39, 0x43, 0x95, 0xe3, 0x07, 0x24,
	0x10, 0x83, 0x51, 0xcf, 0xee, 0x33, 0xea, 0x2c, 0xf4, 0xe3, 0x34, 0x6f, 0x88, 0x18, 0x0f, 0x31,
	0xef, 0x5d, 0x97, 0x9f, 0xbe, 0xd6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xa1, 0x42, 0x80,
	0x90, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterShowcase adds or approves a showcase app in the on-chain registry so
	// its on-chain activity is scored. The signer must be the contest admin
	// configured in genesis params.
	RegisterShowcase(ctx context.Context, in *MsgRegisterShowcase, opts ...grpc.CallOption) (*MsgRegisterShowcaseResponse, error)
	// RemoveShowcase removes a showcase app from the on-chain registry.
	RemoveShowcase(ctx context.Context, in *MsgRemoveShowcase, opts ...grpc.CallOption) (*MsgRemoveShowcaseResponse, error)
	// SetPasskeyEnabled toggles the EXPERIMENTAL WebAuthn/P-256 passkey ante path.
	// Admin-gated. This is the governance switch gating the audit-pending passkey
	// feature; it ships off and can be turned off again if the audit finds issues.
	SetPasskeyEnabled(ctx context.Context, in *MsgSetPasskeyEnabled, opts ...grpc.CallOption) (*MsgSetPasskeyEnabledResponse, error)
	// SetAdmin rotates or revokes (admin = "") the contest admin. Gov-gated: only
	// the x/gov module account may call it (the on-chain governance handoff).
	SetAdmin(ctx context.Context, in *MsgSetAdmin, opts ...grpc.CallOption) (*MsgSetAdminResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterShowcase(ctx context.Context, in *MsgRegisterShowcase, opts ...grpc.CallOption) (*MsgRegisterShowcaseResponse, error) {
	out := new(MsgRegisterShowcaseResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.contest.v1.Msg/RegisterShowcase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveShowcase(ctx context.Context, in *MsgRemoveShowcase, opts ...grpc.CallOption) (*MsgRemoveShowcaseResponse, error) {
	out := new(MsgRemoveShowcaseResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.contest.v1.Msg/RemoveShowcase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetPasskeyEnabled(ctx context.Context, in *MsgSetPasskeyEnabled, opts ...grpc.CallOption) (*MsgSetPasskeyEnabledResponse, error) {
	out := new(MsgSetPasskeyEnabledResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.contest.v1.Msg/SetPasskeyEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetAdmin(ctx context.Context, in *MsgSetAdmin, opts ...grpc.CallOption) (*MsgSetAdminResponse, error) {
	out := new(MsgSetAdminResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.contest.v1.Msg/SetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterShowcase adds or approves a showcase app in the on-chain registry so
	// its on-chain activity is scored. The signer must be the contest admin
	// configured in genesis params.
	RegisterShowcase(context.Context, *MsgRegisterShowcase) (*MsgRegisterShowcaseResponse, error)
	// RemoveShowcase removes a showcase app from the on-chain registry.
	RemoveShowcase(context.Context, *MsgRemoveShowcase) (*MsgRemoveShowcaseResponse, error)
	// SetPasskeyEnabled toggles the EXPERIMENTAL WebAuthn/P-256 passkey ante path.
	// Admin-gated. This is the governance switch gating the audit-pending passkey
	// feature; it ships off and can be turned off again if the audit finds issues.
	SetPasskeyEnabled(context.Context, *MsgSetPasskeyEnabled) (*MsgSetPasskeyEnabledResponse, error)
	// SetAdmin rotates or revokes (admin = "") the contest admin. Gov-gated: only
	// the x/gov module account may call it (the on-chain governance handoff).
	SetAdmin(context.Context, *MsgSetAdmin) (*MsgSetAdminResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterShowcase(ctx context.Context, req *MsgRegisterShowcase) (*MsgRegisterShowcaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterShowcase not implemented")
}
func (*UnimplementedMsgServer) RemoveShowcase(ctx context.Context, req *MsgRemoveShowcase) (*MsgRemoveShowcaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveShowcase not implemented")
}
func (*UnimplementedMsgServer) SetPasskeyEnabled(ctx context.Context, req *MsgSetPasskeyEnabled) (*MsgSetPasskeyEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPasskeyEnabled not implemented")
}
func (*UnimplementedMsgServer) SetAdmin(ctx context.Context, req *MsgSetAdmin) (*MsgSetAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAdmin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterShowcase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterShowcase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterShowcase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.contest.v1.Msg/RegisterShowcase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterShowcase(ctx, req.(*MsgRegisterShowcase))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveShowcase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveShowcase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveShowcase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.contest.v1.Msg/RemoveShowcase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveShowcase(ctx, req.(*MsgRemoveShowcase))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetPasskeyEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetPasskeyEnabled)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetPasskeyEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.contest.v1.Msg/SetPasskeyEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetPasskeyEnabled(ctx, req.(*MsgSetPasskeyEnabled))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.contest.v1.Msg/SetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetAdmin(ctx, req.(*MsgSetAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.contest.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterShowcase",
			Handler:    _Msg_RegisterShowcase_Handler,
		},
		{
			MethodName: "RemoveShowcase",
			Handler:    _Msg_RemoveShowcase_Handler,
		},
		{
			MethodName: "SetPasskeyEnabled",
			Handler:    _Msg_SetPasskeyEnabled_Handler,
		},
		{
			MethodName: "SetAdmin",
			Handler:    _Msg_SetAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/contest/v1/tx.proto",
}

func (m *MsgRegisterShowcase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterShowcase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterShowcase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vm) > 0 {
		i -= len(m.Vm)
		copy(dAtA[i:], m.Vm)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Vm)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Dev) > 0 {
		i -= len(m.Dev)
		copy(dAtA[i:], m.Dev)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Dev)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterShowcaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterShowcaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterShowcaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveShowcase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveShowcase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveShowcase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveShowcaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveShowcaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveShowcaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetPasskeyEnabled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetPasskeyEnabled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetPasskeyEnabled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetPasskeyEnabledResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetPasskeyEnabledResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetPasskeyEnabledResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetAdmin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetAdmin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetAdmin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetAdminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetAdminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetAdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterShowcase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Dev)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Vm)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterShowcaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveShowcase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveShowcaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetPasskeyEnabled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func (m *MsgSetPasskeyEnabledResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetAdmin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetAdminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterShowcase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterShowcase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterShowcase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dev", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dev = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterShowcaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterShowcaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterShowcaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveShowcase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveShowcase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveShowcase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveShowcaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveShowcaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveShowcaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetPasskeyEnabled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetPasskeyEnabled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetPasskeyEnabled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetPasskeyEnabledResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetPasskeyEnabledResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetPasskeyEnabledResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetAdmin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetAdmin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetAdmin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetAdminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetAdminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
