// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/valgrant/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgIssueLocked issues a locked grant to a fresh grantee account (admin-gated).
type MsgIssueLocked struct {
	// admin is the bech32 address authorized to issue grants (params.admin).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// grantee is the bech32 cosmos address receiving the locked account.
	Grantee string `protobuf:"bytes,2,opt,name=grantee,proto3" json:"grantee,omitempty"`
	// locked_amount is the principal in aLIMO (PermanentLockedAccount).
	LockedAmount string `protobuf:"bytes,3,opt,name=locked_amount,json=lockedAmount,proto3" json:"locked_amount,omitempty"`
	// gas_allowance is the liquid gas allowance in aLIMO.
	GasAllowance string `protobuf:"bytes,4,opt,name=gas_allowance,json=gasAllowance,proto3" json:"gas_allowance,omitempty"`
	// validator_operator is the validator operator address (optional).
	ValidatorOperator string `protobuf:"bytes,5,opt,name=validator_operator,json=validatorOperator,proto3" json:"validator_operator,omitempty"`
}

func (m *MsgIssueLocked) Reset()         { *m = MsgIssueLocked{} }
func (m *MsgIssueLocked) String() string { return proto.CompactTextString(m) }
func (*MsgIssueLocked) ProtoMessage()    {}
func (*MsgIssueLocked) Descriptor() ([]byte, []int) {
	return fileDescriptor_f996a8376a7ebb2d, []int{0}
}
func (m *MsgIssueLocked) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueLocked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueLocked.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueLocked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueLocked.Merge(m, src)
}
func (m *MsgIssueLocked) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueLocked) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueLocked.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueLocked proto.InternalMessageInfo

func (m *MsgIssueLocked) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgIssueLocked) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

func (m *MsgIssueLocked) GetLockedAmount() string {
	if m != nil {
		return m.LockedAmount
	}
	return ""
}

func (m *MsgIssueLocked) GetGasAllowance() string {
	if m != nil {
		return m.GasAllowance
	}
	return ""
}

func (m *MsgIssueLocked) GetValidatorOperator() string {
	if m != nil {
		return m.ValidatorOperator
	}
	return ""
}

type MsgIssueLockedResponse struct {
}

func (m *MsgIssueLockedResponse) Reset()         { *m = MsgIssueLockedResponse{} }
func (m *MsgIssueLockedResponse) String() string { return proto.CompactTextString(m) }
func (*MsgIssueLockedResponse) ProtoMessage()    {}
func (*MsgIssueLockedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f996a8376a7ebb2d, []int{1}
}
func (m *MsgIssueLockedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueLockedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueLockedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueLockedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueLockedResponse.Merge(m, src)
}
func (m *MsgIssueLockedResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueLockedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueLockedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueLockedResponse proto.InternalMessageInfo

// MsgClawback claws back a grant from the grantee (admin-gated).
type MsgClawback struct {
	// admin is the bech32 address authorized to clawback (params.admin).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// grantee is the bech32 cosmos address whose grant to clawback.
	Grantee string `protobuf:"bytes,2,opt,name=grantee,proto3" json:"grantee,omitempty"`
}

func (m *MsgClawback) Reset()         { *m = MsgClawback{} }
func (m *MsgClawback) String() string { return proto.CompactTextString(m) }
func (*MsgClawback) ProtoMessage()    {}
func (*MsgClawback) Descriptor() ([]byte, []int) {
	return fileDescriptor_f996a8376a7ebb2d, []int{2}
}
func (m *MsgClawback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClawback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClawback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClawback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClawback.Merge(m, src)
}
func (m *MsgClawback) XXX_Size() int {
	return m.Size()
}
func (m *MsgClawback) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClawback.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClawback proto.InternalMessageInfo

func (m *MsgClawback) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgClawback) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

type MsgClawbackResponse struct {
	// undelegate_amount is the total amount undelegated before the clawback sweep.
	UndelegateAmount string `protobuf:"bytes,1,opt,name=undelegate_amount,json=undelegateAmount,proto3" json:"undelegate_amount,omitempty"`
	// swept_amount is the locked principal swept back to the pool immediately.
	SweptAmount string `protobuf:"bytes,2,opt,name=swept_amount,json=sweptAmount,proto3" json:"swept_amount,omitempty"`
	// pending_amount is principal still unbonding; swept later via EndBlock.
	PendingAmount string `protobuf:"bytes,3,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
}

func (m *MsgClawbackResponse) Reset()         { *m = MsgClawbackResponse{} }
func (m *MsgClawbackResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClawbackResponse) ProtoMessage()    {}
func (*MsgClawbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f996a8376a7ebb2d, []int{3}
}
func (m *MsgClawbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClawbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClawbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClawbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClawbackResponse.Merge(m, src)
}
func (m *MsgClawbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClawbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClawbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClawbackResponse proto.InternalMessageInfo

func (m *MsgClawbackResponse) GetUndelegateAmount() string {
	if m != nil {
		return m.UndelegateAmount
	}
	return ""
}

func (m *MsgClawbackResponse) GetSweptAmount() string {
	if m != nil {
		return m.SweptAmount
	}
	return ""
}

func (m *MsgClawbackResponse) GetPendingAmount() string {
	if m != nil {
		return m.PendingAmount
	}
	return ""
}

// MsgBurnPool permanently destroys LIMO from the valgrant reserve pool
// (admin-gated). The burned coins are removed from the module account AND from
// total supply.
type MsgBurnPool struct {
	// admin is the bech32 address authorized to burn the pool (params.admin).
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// amount is the aLIMO amount to destroy. "0" or empty burns the ENTIRE current
	// pool balance.
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgBurnPool) Reset()         { *m = MsgBurnPool{} }
func (m *MsgBurnPool) String() string { return proto.CompactTextString(m) }
func (*MsgBurnPool) ProtoMessage()    {}
func (*MsgBurnPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_f996a8376a7ebb2d, []int{4}
}
func (m *MsgBurnPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnPool.Merge(m, src)
}
func (m *MsgBurnPool) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnPool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnPool proto.InternalMessageInfo

func (m *MsgBurnPool) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgBurnPool) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgBurnPoolResponse struct {
	// burned is the aLIMO amount actually destroyed (removed from total supply).
	Burned string `protobuf:"bytes,1,opt,name=burned,proto3" json:"burned,omitempty"`
}

func (m *MsgBurnPoolResponse) Reset()         { *m = MsgBurnPoolResponse{} }
func (m *MsgBurnPoolResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBurnPoolResponse) ProtoMessage()    {}
func (*MsgBurnPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f996a8376a7ebb2d, []int{5}
}
func (m *MsgBurnPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnPoolResponse.Merge(m, src)
}
func (m *MsgBurnPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnPoolResponse proto.InternalMessageInfo

func (m *MsgBurnPoolResponse) GetBurned() string {
	if m != nil {
		return m.Burned
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgIssueLocked)(nil), "cosmos.evm.valgrant.v1.MsgIssueLocked")
	proto.RegisterType((*MsgIssueLockedResponse)(nil), "cosmos.evm.valgrant.v1.MsgIssueLockedResponse")
	proto.RegisterType((*MsgClawback)(nil), "cosmos.evm.valgrant.v1.MsgClawback")
	proto.RegisterType((*MsgClawbackResponse)(nil), "cosmos.evm.valgrant.v1.MsgClawbackResponse")
	proto.RegisterType((*MsgBurnPool)(nil), "cosmos.evm.valgrant.v1.MsgBurnPool")
	proto.RegisterType((*MsgBurnPoolResponse)(nil), "cosmos.evm.valgrant.v1.MsgBurnPoolResponse")
}

func init() { proto.RegisterFile("cosmos/evm/valgrant/v1/tx.proto", fileDescriptor_f996a8376a7ebb2d) }

var fileDescriptor_f996a8376a7ebb2d = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0xe3, 0x94, 0x04, 0xb8, 0xb4, 0x15, 0x31, 0x55, 0x30, 0x19, 0x5c, 0x70, 0x45, 0x85,
	0x52, 0xc5, 0x56, 0xca, 0xd6, 0x89, 0x84, 0x09, 0x89, 0x08, 0x14, 0x36, 0x84, 0x14, 0x5d, 0xe2,
	0xd3, 0x61, 0xd5, 0xbe, 0xb3, 0x7c, 0x67, 0xa7, 0x6c, 0x08, 0x89, 0x05, 0x31, 0xf0, 0x11, 0xe0,
	0x13, 0x90, 0x81, 0x0f, 0xc1, 0x58, 0x31, 0x31, 0xa2, 0x64, 0xc8, 0xd7, 0x40, 0xb9, 0x3f, 0x6e,
	0x8c, 0x4a, 0x08, 0x0b, 0x4b, 0xe4, 0xf7, 0x79, 0x7f, 0xf7, 0xfa, 0xf1, 0xf3, 0xda, 0x01, 0xfb,
	0x63, 0xca, 0x22, 0xca, 0x3c, 0x94, 0x45, 0x5e, 0x06, 0x43, 0x9c, 0x40, 0xc2, 0xbd, 0xac, 0xe3,
	0xf1, 0x33, 0x37, 0x4e, 0x28, 0xa7, 0x66, 0x43, 0x02, 0x2e, 0xca, 0x22, 0x57, 0x03, 0x6e, 0xd6,
	0x69, 0xd6, 0x61, 0x14, 0x10, 0xea, 0x89, 0x5f, 0x89, 0x36, 0x6f, 0xa9, 0x59, 0x11, 0xc3, 0xcb,
	0x11, 0x11, 0xc3, 0xaa, 0x71, 0x5b, 0x36, 0x86, 0xa2, 0xf2, 0xd4, 0x40, 0xd9, 0xda, 0xc3, 0x14,
	0x53, 0xa9, 0x2f, 0xaf, 0xa4, 0xea, 0x7c, 0x2a, 0x83, 0xdd, 0x3e, 0xc3, 0x8f, 0x19, 0x4b, 0xd1,
	0x13, 0x3a, 0x3e, 0x45, 0xbe, 0xe9, 0x82, 0x0a, 0xf4, 0xa3, 0x80, 0x58, 0xc6, 0x1d, 0xe3, 0xfe,
	0xf5, 0x9e, 0xf5, 0xfd, 0x6b, 0x7b, 0x4f, 0x4d, 0xea, 0xfa, 0x7e, 0x82, 0x18, 0x7b, 0xce, 0x93,
	0x80, 0xe0, 0x81, 0xc4, 0xcc, 0x63, 0x70, 0x55, 0x78, 0x45, 0xc8, 0x2a, 0xff, 0xe5, 0x84, 0x06,
	0xcd, 0x03, 0xb0, 0x13, 0x8a, 0xbb, 0x0d, 0x61, 0x44, 0x53, 0xc2, 0xad, 0xad, 0xe5, 0xc9, 0xc1,
	0xb6, 0x14, 0xbb, 0x42, 0x5b, 0x42, 0x18, 0xb2, 0x21, 0x0c, 0x43, 0x3a, 0x81, 0x64, 0x8c, 0xac,
	0x2b, 0x12, 0xc2, 0x90, 0x75, 0xb5, 0x66, 0xb6, 0x81, 0x99, 0xc1, 0x30, 0xf0, 0x21, 0xa7, 0xc9,
	0x90, 0xc6, 0x28, 0x59, 0x5e, 0x58, 0x15, 0x41, 0xd6, 0xf3, 0xce, 0x53, 0xd5, 0x38, 0xe9, 0xbc,
	0x5d, 0x4c, 0x5b, 0xd2, 0xf8, 0xfb, 0xc5, 0xb4, 0xe5, 0x5c, 0xb6, 0x94, 0x62, 0x1e, 0x8e, 0x05,
	0x1a, 0x45, 0x65, 0x80, 0x58, 0x4c, 0x09, 0x43, 0xce, 0x67, 0x03, 0xd4, 0xfa, 0x0c, 0x3f, 0x0a,
	0xe1, 0x64, 0x04, 0xc7, 0xa7, 0xff, 0x23, 0xb9, 0x13, 0xb7, 0xf8, 0x00, 0xfb, 0x7f, 0x78, 0x00,
	0xed, 0xc9, 0xf9, 0x60, 0x80, 0x9b, 0x2b, 0xb5, 0xf6, 0x6e, 0x1e, 0x81, 0x7a, 0x4a, 0x7c, 0x14,
	0x22, 0x0c, 0x39, 0xd2, 0x5b, 0x10, 0xbe, 0x07, 0x37, 0x2e, 0x1a, 0x6a, 0x13, 0x77, 0xc1, 0x36,
	0x9b, 0xa0, 0x98, 0x6b, 0x4e, 0xb8, 0x1d, 0xd4, 0x84, 0xa6, 0x90, 0x7b, 0x60, 0x37, 0x46, 0xc4,
	0x0f, 0x08, 0x2e, 0xae, 0x74, 0x47, 0xa9, 0x12, 0x73, 0xde, 0xc9, 0xc8, 0x7a, 0x69, 0x42, 0x9e,
	0x51, 0x1a, 0xfe, 0x73, 0x64, 0x0d, 0x50, 0x2d, 0x78, 0x50, 0xd5, 0xa6, 0xb1, 0xe8, 0xfb, 0x3a,
	0x6d, 0x91, 0x8a, 0x2e, 0xf3, 0x54, 0x1a, 0xa0, 0x3a, 0x4a, 0x13, 0x82, 0x7c, 0x15, 0x85, 0xaa,
	0x8e, 0xbf, 0x94, 0xc1, 0x56, 0x9f, 0x61, 0x13, 0x81, 0xda, 0xea, 0xa7, 0x72, 0xe8, 0x5e, 0xfe,
	0xcd, 0xba, 0xc5, 0x17, 0xa6, 0xe9, 0x6e, 0xc6, 0xe5, 0x36, 0x5e, 0x82, 0x6b, 0xf9, 0x4b, 0x75,
	0xb0, 0xe6, 0xac, 0x86, 0x9a, 0x47, 0x1b, 0x40, 0xab, 0xd3, 0xf3, 0xfc, 0xd7, 0x4d, 0xd7, 0xd0,
	0xda, 0xe9, 0xbf, 0x47, 0xd8, 0xac, 0xbc, 0x59, 0x4c, 0x5b, 0x46, 0xef, 0xe1, 0xb7, 0x99, 0x6d,
	0x9c, 0xcf, 0x6c, 0xe3, 0xe7, 0xcc, 0x36, 0x3e, 0xce, 0xed, 0xd2, 0xf9, 0xdc, 0x2e, 0xfd, 0x98,
	0xdb, 0xa5, 0x17, 0x87, 0x38, 0xe0, 0xaf, 0xd2, 0x91, 0x3b, 0xa6, 0x91, 0xb7, 0xb2, 0xa6, 0xb3,
	0x8b, 0x45, 0xf1, 0xd7, 0x31, 0x62, 0xa3, 0xaa, 0xf8, 0x87, 0x7a, 0xf0, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0xea, 0xc6, 0x65, 0xb8, 0x39, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// IssueLocked creates a PermanentLockedAccount for a validator candidate
	// (admin-gated). Funds it with locked principal + a small liquid gas
	// allowance, both sent from the valgrant module reserve pool.
	IssueLocked(ctx context.Context, in *MsgIssueLocked, opts ...grpc.CallOption) (*MsgIssueLockedResponse, error)
	// Clawback force-undelegates the grantee's delegations and sweeps the locked
	// principal back into the valgrant pool (admin-gated), leaving earned rewards
	// and the gas allowance with the grantee, then marks the grant revoked.
	Clawback(ctx context.Context, in *MsgClawback, opts ...grpc.CallOption) (*MsgClawbackResponse, error)
	// BurnPool permanently DESTROYS LIMO from the valgrant reserve pool
	// (admin-gated): the coins are removed from the module account AND from total
	// supply, proving reclaimed bootstrap capital never comes back to anyone.
	BurnPool(ctx context.Context, in *MsgBurnPool, opts ...grpc.CallOption) (*MsgBurnPoolResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) IssueLocked(ctx context.Context, in *MsgIssueLocked, opts ...grpc.CallOption) (*MsgIssueLockedResponse, error) {
	out := new(MsgIssueLockedResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.valgrant.v1.Msg/IssueLocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Clawback(ctx context.Context, in *MsgClawback, opts ...grpc.CallOption) (*MsgClawbackResponse, error) {
	out := new(MsgClawbackResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.valgrant.v1.Msg/Clawback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnPool(ctx context.Context, in *MsgBurnPool, opts ...grpc.CallOption) (*MsgBurnPoolResponse, error) {
	out := new(MsgBurnPoolResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.valgrant.v1.Msg/BurnPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// IssueLocked creates a PermanentLockedAccount for a validator candidate
	// (admin-gated). Funds it with locked principal + a small liquid gas
	// allowance, both sent from the valgrant module reserve pool.
	IssueLocked(context.Context, *MsgIssueLocked) (*MsgIssueLockedResponse, error)
	// Clawback force-undelegates the grantee's delegations and sweeps the locked
	// principal back into the valgrant pool (admin-gated), leaving earned rewards
	// and the gas allowance with the grantee, then marks the grant revoked.
	Clawback(context.Context, *MsgClawback) (*MsgClawbackResponse, error)
	// BurnPool permanently DESTROYS LIMO from the valgrant reserve pool
	// (admin-gated): the coins are removed from the module account AND from total
	// supply, proving reclaimed bootstrap capital never comes back to anyone.
	BurnPool(context.Context, *MsgBurnPool) (*MsgBurnPoolResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) IssueLocked(ctx context.Context, req *MsgIssueLocked) (*MsgIssueLockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLocked not implemented")
}
func (*UnimplementedMsgServer) Clawback(ctx context.Context, req *MsgClawback) (*MsgClawbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clawback not implemented")
}
func (*UnimplementedMsgServer) BurnPool(ctx context.Context, req *MsgBurnPool) (*MsgBurnPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnPool not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_IssueLocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssueLocked)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueLocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.valgrant.v1.Msg/IssueLocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueLocked(ctx, req.(*MsgIssueLocked))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Clawback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClawback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Clawback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.valgrant.v1.Msg/Clawback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Clawback(ctx, req.(*MsgClawback))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurnPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.valgrant.v1.Msg/BurnPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnPool(ctx, req.(*MsgBurnPool))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.valgrant.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueLocked",
			Handler:    _Msg_IssueLocked_Handler,
		},
		{
			MethodName: "Clawback",
			Handler:    _Msg_Clawback_Handler,
		},
		{
			MethodName: "BurnPool",
			Handler:    _Msg_BurnPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/valgrant/v1/tx.proto",
}

func (m *MsgIssueLocked) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueLocked) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueLocked) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorOperator) > 0 {
		i -= len(m.ValidatorOperator)
		copy(dAtA[i:], m.ValidatorOperator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorOperator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GasAllowance) > 0 {
		i -= len(m.GasAllowance)
		copy(dAtA[i:], m.GasAllowance)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GasAllowance)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LockedAmount) > 0 {
		i -= len(m.LockedAmount)
		copy(dAtA[i:], m.LockedAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LockedAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Grantee) > 0 {
		i -= len(m.Grantee)
		copy(dAtA[i:], m.Grantee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Grantee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIssueLockedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueLockedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueLockedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClawback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClawback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClawback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Grantee) > 0 {
		i -= len(m.Grantee)
		copy(dAtA[i:], m.Grantee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Grantee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClawbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClawbackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClawbackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingAmount) > 0 {
		i -= len(m.PendingAmount)
		copy(dAtA[i:], m.PendingAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PendingAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SweptAmount) > 0 {
		i -= len(m.SweptAmount)
		copy(dAtA[i:], m.SweptAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SweptAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UndelegateAmount) > 0 {
		i -= len(m.UndelegateAmount)
		copy(dAtA[i:], m.UndelegateAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UndelegateAmount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBurnPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBurnPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Burned) > 0 {
		i -= len(m.Burned)
		copy(dAtA[i:], m.Burned)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Burned)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgIssueLocked) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Grantee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LockedAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GasAllowance)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ValidatorOperator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgIssueLockedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClawback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Grantee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClawbackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UndelegateAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SweptAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PendingAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBurnPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBurnPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Burned)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgIssueLocked) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueLocked: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueLocked: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grantee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grantee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockedAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasAllowance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasAllowance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorOperator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorOperator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueLockedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueLockedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueLockedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClawback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClawback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClawback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grantee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grantee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClawbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClawbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClawbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UndelegateAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UndelegateAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SweptAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SweptAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Burned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Burned = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
